version: "3.9"

services:

  # https://hub.docker.com/r/xhofe/alist
  # https://alist.nn.ci/guide/install/docker.html#release-version
  # 当前页的配置基于 qnap ts551 v5.x 版本系统的容器管理配置
  alist:
    image: registry.dockermirror.com/xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=0 # Find your own user PUID and group PGID. https://docs.linuxserver.io/general/understanding-puid-and-pgid
      - PGID=0 # When using volumes (-v flags) permissions issues can arise between the host OS and the container, we avoid this issue by allowing you to specify the user PUID and group PGID.
      - UMASK=022
      - TZ=Asia/Shanghai
      - Qbittorrent_ADDRESS=qbittorrentee
      - Qbittorrent_PORT=8181
    volumes:
    #  - ${PWD}/alist/data:/opt/alist/data
       - /share/Container/alist/data:/opt/alist/data
    ports:
      - 5244:5244 
    restart: unless-stopped
    networks:
      - alistbridge

  # aria2的部分由https://github.com/zptpower1/Aria2-Pro-Docker/blob/master/docker-compose.yml 单独配置
  # # Aria2-pro-docker official guide: https://github.com/P3TERX/Aria2-Pro-Docker/blob/master/docker-compose.yml
  # Aria2-Pro:
  #   container_name: aria2-pro
  #   image: registry.dockermirror.com/p3terx/aria2-pro:latest
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - UMASK_SET=022
  #     - RPC_SECRET=P3TERX # Please set your own RPC secret.
  #     - RPC_PORT=6800
  #     - LISTEN_PORT=6888
  #     - DISK_CACHE=64M
  #     - IPV6_MODE=false
  #     - UPDATE_TRACKERS=true
  #     - CUSTOM_TRACKER_URL=
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - /Container/aria2/config:/config       # Aria2 Config
  #     - /Downloads:/downloads # Aria2 Default Download Path
  #     - /Container/aria2/data:/opt/alist/data # Aria2 Data folder
  #   # If you use host network mode, then no port mapping is required.
  #   # This is the easiest way to use IPv6 networks.
  #   network_mode: host
  #   # networks:
  #   #   - alistbridge
  #   # ports:
  #   #   - "6800:6800"
  #   #   - "6888:6888"
  #   #   - "6888:6888/udp"
  #   restart: unless-stopped
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1m
    

  # AriaNg:
  #   image: registry.dockermirror.com/p3terx/ariang:latest
  #   container_name: aria-ng
  #   # environment:
  #   #  - PUID=0
  #   #  - PGID=0
  #   command: --port 6880 --ipv6
  #   networks:
  #     - alistbridge
  #   ports:
  #     - "6880:6880"
  #   restart: unless-stopped
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 1m

  # https://hub.docker.com/r/superng6/qbittorrentee
  qbittorrent:
    image: registry.dockermirror.com/superng6/qbittorrentee:latest
    container_name: qbittorrentee
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUIPORT=8181
    volumes:
      - /share/Container/qbittorrent/config:/config       # config
      - /share/Downloads:/downloads # Downloads
      - /share/Container/qbittorrent/data:/opt/alist/data # Data
    networks:
      - alistbridge
    ports:
      - 8181:8181
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
networks:
  alistbridge:
    driver: bridge
